<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="5CD93439TM" failures="2" tests="2" name="ValidateTitle" time="11.288" errors="0" timestamp="06 Sep 2021 13:16:38 GMT">
  <testcase classname="Academy.Sec29_E2E.Validatetitle" name="ValidateHeader" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Academy.Sec29_E2E.Validatetitle.ValidateHeader(Validatetitle.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ValidateHeader -->
  <testcase classname="Academy.Sec29_E2E.Validatetitle" name="ValidateTitle" time="0.232">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;...&amp;gt; but was:&amp;lt;...123&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<...123>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at Academy.Sec29_E2E.Validatetitle.ValidateTitle(Validatetitle.java:42)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ValidateTitle -->
</testsuite> <!-- ValidateTitle -->
